#!/usr/bin/env python
"""
Build a DeepLabCut project from blob-tracker labels.

Only one keypoint is supervised. The blob centroid is the animal's centre of
mass, so `mouse_center` is filled and every other SuperAnimal keypoint is left
NaN -- DLC masks missing targets in the loss, so the pretrained 27-keypoint head
is preserved and only the one keypoint we actually know is trained. The
consequence is stated plainly: the resulting network tracks position, not
posture. Head direction is not recoverable this way and needs hand labels.

The keypoint list is read from an existing prediction .h5 rather than hardcoded,
so it always matches the model the fine-tune starts from.

  python dlc_project_from_blobs.py \
      --manifest C_trainframes_manifest.csv --frames C_trainframes \
      --from-h5 C_superanimal_..._fpn-004.h5 \
      --video /scratch/jma819/T_maze_recordings/behaviorVIdeos/C.avi \
      --project TmazeBlob --scorer blobtracker --out-root .
"""
import argparse
import datetime as dt
import os
import shutil

import numpy as np
import pandas as pd


CONFIG = """\
# DeepLabCut project generated by dlc_project_from_blobs.py
# Labels are blob-tracker centroids: `{primary}` only, every other keypoint NaN.
# This project trains POSITION, not posture.
Task: {task}
scorer: {scorer}
date: {date}
multianimalproject: false
identity:
project_path: {project_path}
engine: pytorch

video_sets:
  {video}:
    crop: 0, {w}, 0, {h}

bodyparts:
{bodyparts}

skeleton:
skeleton_color: black
pcutoff: 0.6
dotsize: 4
alphavalue: 0.7
colormap: rainbow

TrainingFraction:
- {train_frac}
iteration: 0
default_net_type: top_down_hrnet_w32
default_augmenter: default
snapshotindex: -1
batch_size: 8

cropping: false
x1: 0
x2: {w}
y1: 0
y2: {h}

corner2move2:
- 50
- 50
move2corner: true
start: 0
stop: 1
numframes2pick: {nframes}
alphavalue: 0.7
"""


def bodyparts_from_h5(path):
    df = pd.read_hdf(path)
    lv = df.columns.names
    if "bodyparts" in lv:
        bp = list(dict.fromkeys(df.columns.get_level_values("bodyparts")))
    else:
        bp = list(dict.fromkeys(df.columns.get_level_values(-2)))
    return [b for b in bp if b not in ("", None)]


def main():
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--manifest", required=True)
    p.add_argument("--frames", required=True, help="directory of extracted PNGs")
    p.add_argument("--from-h5", required=True, help="prediction .h5 to take keypoint names from")
    p.add_argument("--video", required=True, help="path the video will have on the training machine")
    p.add_argument("--project", default="TmazeBlob")
    p.add_argument("--scorer", default="blobtracker")
    p.add_argument("--primary", default="mouse_center")
    p.add_argument("--out-root", default=".")
    p.add_argument("--train-frac", type=float, default=0.9)
    p.add_argument("--width", type=int, default=720)
    p.add_argument("--height", type=int, default=480)
    a = p.parse_args()

    bp = bodyparts_from_h5(a.from_h5)
    if a.primary not in bp:
        raise SystemExit(f"{a.primary} not among keypoints in {a.from_h5}: {bp}")
    M = pd.read_csv(a.manifest)
    stem = os.path.splitext(os.path.basename(a.video))[0]
    date = dt.date.today().strftime("%Y-%m-%d")
    proj = os.path.join(os.path.abspath(a.out_root),
                        f"{a.project}-{a.scorer}-{date}")
    ldir = os.path.join(proj, "labeled-data", stem)
    for d in ("training-datasets", "dlc-models", "videos", "labeled-data"):
        os.makedirs(os.path.join(proj, d), exist_ok=True)
    os.makedirs(ldir, exist_ok=True)

    n_copied = 0
    for nm in M.image:
        src = os.path.join(a.frames, nm)
        if os.path.exists(src):
            shutil.copy2(src, os.path.join(ldir, nm))
            n_copied += 1
    if n_copied != len(M):
        raise SystemExit(f"only {n_copied} of {len(M)} manifest images found in {a.frames}")

    cols = pd.MultiIndex.from_product([[a.scorer], bp, ["x", "y"]],
                                      names=["scorer", "bodyparts", "coords"])
    idx = pd.MultiIndex.from_tuples(
        [("labeled-data", stem, nm) for nm in M.image])
    D = pd.DataFrame(np.nan, index=idx, columns=cols, dtype=float)
    D[(a.scorer, a.primary, "x")] = M.x.to_numpy()
    D[(a.scorer, a.primary, "y")] = M.y.to_numpy()
    h5 = os.path.join(ldir, f"CollectedData_{a.scorer}.h5")
    D.to_hdf(h5, key="df_with_missing", mode="w")
    D.to_csv(os.path.join(ldir, f"CollectedData_{a.scorer}.csv"))

    open(os.path.join(proj, "config.yaml"), "w").write(CONFIG.format(
        task=a.project, scorer=a.scorer, date=date, project_path=proj,
        video=a.video, w=a.width, h=a.height, primary=a.primary,
        bodyparts="\n".join(f"- {b}" for b in bp),
        train_frac=a.train_frac, nframes=len(M)))

    back = pd.read_hdf(h5)
    filled = int(np.isfinite(back[(a.scorer, a.primary, "x")]).sum())
    print(f"project: {proj}")
    print(f"keypoints declared: {len(bp)} (from {os.path.basename(a.from_h5)})")
    print(f"images: {n_copied}; rows in CollectedData: {len(back)}; "
          f"{a.primary} labelled in {filled}")
    print(f"other keypoints left NaN: "
          f"{int(back.drop(columns=a.primary, level=1).isna().all().all())} (1 = all NaN, as intended)")
    print(f"config: {os.path.join(proj, 'config.yaml')}")
    print("\nnext, on the training machine:")
    print(f"  python dlc_finetune.py --config {os.path.join(proj, 'config.yaml')}")


if __name__ == "__main__":
    main()
